version: "3"

services:
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    networks:
      - kafka
    depends_on:
      - zookeeper
      - kafka-0
      - kafka-1
      - kafka-2
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-0:9092,kafka-1:9092,kafka-2:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_JMXPORT: 9997
    healthcheck:
      test: [
          "CMD",
          "curl",
          "-f",
          "http://127.0.0.1:8080/"
      ]
      interval: 10s
      timeout: 5s
      retries: 30
